apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # This points to the Prometheus container
    isDefault: true
    editable: true
